// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class AddtocartTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void addtocart() {
    driver.get("https://cms.demo.katalon.com/");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.cssSelector(".post-54 .button")).click();
    driver.findElement(By.cssSelector(".post-26 .button")).click();
    driver.findElement(By.cssSelector(".post-27 .button")).click();
    driver.findElement(By.cssSelector(".site-branding")).click();
    driver.findElement(By.xpath("//main[@id=\'main\']/form/span/span/span/span")).click();
    driver.findElement(By.cssSelector(".post-14 .button")).click();
    driver.findElement(By.cssSelector(".page-item-8 > a")).click();
    driver.findElement(By.linkText("×")).click();
    driver.findElement(By.linkText("×")).click();
    js.executeScript("window.scrollTo(0,284)");
    driver.findElement(By.cssSelector(".woocommerce-cart-form__cart-item:nth-child(4) .remove")).click();
  }
}
